### ISSUE TITLE
Adding `:posts` and `:pages` to params via :extend-params-fn does not behave as expected

### ISSUE THREAD

**Issue by ieugen** [cryogen-project/cryogen-core#156] opened 2020-12-23 19:12 UTC
I was trying to make a page that displays articles and  used `compile-assets-timed {:extend-params-fn extend-params}` . 
I found out that did not work as expected and I spent a few hours trying to figure it out.

Most changes are in this changeset https://github.com/ieugen/ieugen.ro/commit/2ced76497244a7ddac17ec10ddf8db6b87a314ce . 

You can check out that commit and when doing `lein ring server` you should see that articles are not visible. 

Sometimes, when the articles list is visible, no content is in the pages and posts. 

````
(defn extend-params [params {:keys [pages posts] :as other-pages}]
  (let [tag-count (->> (:posts-by-tag other-pages)
                       (map (fn [[k v]] [k (count v)]))
                       (into {}))
        tags-with-count (update
                         params :tags
                         #(map (fn [t] (assoc t :count (tag-count (:name t)))) %))
        new-site-data (assoc tags-with-count :all-my-posts posts :all-my-pages pages)]
    new-site-data))
````

I found out that the code does not work if I pass `:posts` and or `:pages` keys. 
The content disappears. 

I fixed it by passing other names, like `:all-my-posts`. 
It was not obvious and it behaved very strange.

**Comment by holyjak** [comment] 2021-10-05 08:52
Why would you add posts and pages to params? It is already there: https://github.com/cryogen-project/cryogen-core/blob/0.4.0/src/cryogen_core/compiler.clj#L648

> I found out that the code does not work if I pass :posts and or :pages keys.
> The content disappears.
I do not really know what that means. According to the code, if you add these, they will be overriden, see the linked code.

I guess that when you write an `:extend-params-fn`, we should mandate that you look at the code where it is used to understand better what is going on....

So, is this still an issue or can we close this?

**Comment by holyjak** [comment] 2021-10-05 09:18
(deleted my previous comment since it was wrong)

Adding posts/pages via `:extend-params-fn` is possible and simple, see https://github.com/holyjak/tmp-demo-cryogen-posts-everywhere/commit/0d7654f816f669b88b313c37aaeecb90d9798437

**Comment by holyjak** [comment] 2021-10-05 10:10
Ok, it is some interesting timing issues. *Sometimes* the `:post` only has `:content-dom` instead of the stringified `:content` - when I compile the same thing repeatedly, it is random which one I get.

**Comment by holyjak** [comment] 2021-10-05 10:18
This is the cause https://github.com/cryogen-project/cryogen-core/blob/0.4.0/src/cryogen_core/compiler.clj#L328 - if there is posts than we htmlize that and not post. (This is for the tags and previews pages)

I need to explore whether we can safely change the ordering.

**Closed** 2021-10-05 11:09 UTC
